// Generated by gencpp from file qbo_arduqbo/BaseStopRequest.msg
// DO NOT EDIT!


#ifndef QBO_ARDUQBO_MESSAGE_BASESTOPREQUEST_H
#define QBO_ARDUQBO_MESSAGE_BASESTOPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qbo_arduqbo
{
template <class ContainerAllocator>
struct BaseStopRequest_
{
  typedef BaseStopRequest_<ContainerAllocator> Type;

  BaseStopRequest_()
    : sender()
    , state(false)  {
    }
  BaseStopRequest_(const ContainerAllocator& _alloc)
    : sender(_alloc)
    , state(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sender_type;
  _sender_type sender;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BaseStopRequest_

typedef ::qbo_arduqbo::BaseStopRequest_<std::allocator<void> > BaseStopRequest;

typedef boost::shared_ptr< ::qbo_arduqbo::BaseStopRequest > BaseStopRequestPtr;
typedef boost::shared_ptr< ::qbo_arduqbo::BaseStopRequest const> BaseStopRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qbo_arduqbo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'qbo_arduqbo': ['/home/qbo/Desktop/melodia/src/qbo_arduqbo/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adc1836ec05769e51272f3bf2b237d1d";
  }

  static const char* value(const ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xadc1836ec05769e5ULL;
  static const uint64_t static_value2 = 0x1272f3bf2b237d1dULL;
};

template<class ContainerAllocator>
struct DataType< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qbo_arduqbo/BaseStopRequest";
  }

  static const char* value(const ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sender\n"
"bool state\n"
;
  }

  static const char* value(const ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BaseStopRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator>& v)
  {
    s << indent << "sender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sender);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QBO_ARDUQBO_MESSAGE_BASESTOPREQUEST_H
