// Generated by gencpp from file qbo_arduqbo/BaseStop.msg
// DO NOT EDIT!


#ifndef QBO_ARDUQBO_MESSAGE_BASESTOP_H
#define QBO_ARDUQBO_MESSAGE_BASESTOP_H

#include <ros/service_traits.h>


#include <qbo_arduqbo/BaseStopRequest.h>
#include <qbo_arduqbo/BaseStopResponse.h>


namespace qbo_arduqbo
{

struct BaseStop
{

typedef BaseStopRequest Request;
typedef BaseStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BaseStop
} // namespace qbo_arduqbo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qbo_arduqbo::BaseStop > {
  static const char* value()
  {
    return "adc1836ec05769e51272f3bf2b237d1d";
  }

  static const char* value(const ::qbo_arduqbo::BaseStop&) { return value(); }
};

template<>
struct DataType< ::qbo_arduqbo::BaseStop > {
  static const char* value()
  {
    return "qbo_arduqbo/BaseStop";
  }

  static const char* value(const ::qbo_arduqbo::BaseStop&) { return value(); }
};


// service_traits::MD5Sum< ::qbo_arduqbo::BaseStopRequest> should match 
// service_traits::MD5Sum< ::qbo_arduqbo::BaseStop > 
template<>
struct MD5Sum< ::qbo_arduqbo::BaseStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_arduqbo::BaseStop >::value();
  }
  static const char* value(const ::qbo_arduqbo::BaseStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_arduqbo::BaseStopRequest> should match 
// service_traits::DataType< ::qbo_arduqbo::BaseStop > 
template<>
struct DataType< ::qbo_arduqbo::BaseStopRequest>
{
  static const char* value()
  {
    return DataType< ::qbo_arduqbo::BaseStop >::value();
  }
  static const char* value(const ::qbo_arduqbo::BaseStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qbo_arduqbo::BaseStopResponse> should match 
// service_traits::MD5Sum< ::qbo_arduqbo::BaseStop > 
template<>
struct MD5Sum< ::qbo_arduqbo::BaseStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_arduqbo::BaseStop >::value();
  }
  static const char* value(const ::qbo_arduqbo::BaseStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_arduqbo::BaseStopResponse> should match 
// service_traits::DataType< ::qbo_arduqbo::BaseStop > 
template<>
struct DataType< ::qbo_arduqbo::BaseStopResponse>
{
  static const char* value()
  {
    return DataType< ::qbo_arduqbo::BaseStop >::value();
  }
  static const char* value(const ::qbo_arduqbo::BaseStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QBO_ARDUQBO_MESSAGE_BASESTOP_H
