// Generated by gencpp from file qbo_face_msgs/FacePosAndDist.msg
// DO NOT EDIT!


#ifndef QBO_FACE_MSGS_MESSAGE_FACEPOSANDDIST_H
#define QBO_FACE_MSGS_MESSAGE_FACEPOSANDDIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace qbo_face_msgs
{
template <class ContainerAllocator>
struct FacePosAndDist_
{
  typedef FacePosAndDist_<ContainerAllocator> Type;

  FacePosAndDist_()
    : header()
    , u(0.0)
    , v(0.0)
    , distance_to_head(0.0)
    , image_width(0)
    , image_height(0)
    , face_detected(false)
    , type_of_tracking()  {
    }
  FacePosAndDist_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , u(0.0)
    , v(0.0)
    , distance_to_head(0.0)
    , image_width(0)
    , image_height(0)
    , face_detected(false)
    , type_of_tracking(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _u_type;
  _u_type u;

   typedef float _v_type;
  _v_type v;

   typedef float _distance_to_head_type;
  _distance_to_head_type distance_to_head;

   typedef int32_t _image_width_type;
  _image_width_type image_width;

   typedef int32_t _image_height_type;
  _image_height_type image_height;

   typedef uint8_t _face_detected_type;
  _face_detected_type face_detected;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_of_tracking_type;
  _type_of_tracking_type type_of_tracking;





  typedef boost::shared_ptr< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> const> ConstPtr;

}; // struct FacePosAndDist_

typedef ::qbo_face_msgs::FacePosAndDist_<std::allocator<void> > FacePosAndDist;

typedef boost::shared_ptr< ::qbo_face_msgs::FacePosAndDist > FacePosAndDistPtr;
typedef boost::shared_ptr< ::qbo_face_msgs::FacePosAndDist const> FacePosAndDistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qbo_face_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'qbo_face_msgs': ['/home/qbo/Desktop/melodia/src/qbo_face_msgs/msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25b96c14697425c4e9c9aa5538bcad7c";
  }

  static const char* value(const ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25b96c14697425c4ULL;
  static const uint64_t static_value2 = 0xe9c9aa5538bcad7cULL;
};

template<class ContainerAllocator>
struct DataType< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qbo_face_msgs/FacePosAndDist";
  }

  static const char* value(const ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Software License Agreement (LGPL v2.1 License)\n"
"#\n"
"# Copyright (c) 2012 Thecorpora, S.L.\n"
"#\n"
"# This library is free software; you can redistribute it and/or modify \n"
"# it under the terms of the GNU Lesser General Public License as published\n"
"# by the Free Software Foundation; either version 2.1 of the License, \n"
"# or (at your option) any later version.\n"
"#\n"
"# This library is distributed in the hope that it will be useful, but \n"
"# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY \n"
"# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public \n"
"# License for more details.\n"
"#  \n"
"# You should have received a copy of the GNU General Public License \n"
"# along with this program; if not, write to the Free Software \n"
"# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, \n"
"# MA 02110-1301, USA.\n"
"\n"
"Header header\n"
"float32 u\n"
"float32 v\n"
"float32 distance_to_head\n"
"int32 image_width\n"
"int32 image_height\n"
"bool face_detected\n"
"string type_of_tracking\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.u);
      stream.next(m.v);
      stream.next(m.distance_to_head);
      stream.next(m.image_width);
      stream.next(m.image_height);
      stream.next(m.face_detected);
      stream.next(m.type_of_tracking);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FacePosAndDist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qbo_face_msgs::FacePosAndDist_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "u: ";
    Printer<float>::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
    s << indent << "distance_to_head: ";
    Printer<float>::stream(s, indent + "  ", v.distance_to_head);
    s << indent << "image_width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.image_width);
    s << indent << "image_height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.image_height);
    s << indent << "face_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.face_detected);
    s << indent << "type_of_tracking: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type_of_tracking);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QBO_FACE_MSGS_MESSAGE_FACEPOSANDDIST_H
