// Generated by gencpp from file qbo_face_msgs/GetNameResponse.msg
// DO NOT EDIT!


#ifndef QBO_FACE_MSGS_MESSAGE_GETNAMERESPONSE_H
#define QBO_FACE_MSGS_MESSAGE_GETNAMERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qbo_face_msgs
{
template <class ContainerAllocator>
struct GetNameResponse_
{
  typedef GetNameResponse_<ContainerAllocator> Type;

  GetNameResponse_()
    : name()
    , recognized(false)  {
    }
  GetNameResponse_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , recognized(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _recognized_type;
  _recognized_type recognized;





  typedef boost::shared_ptr< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetNameResponse_

typedef ::qbo_face_msgs::GetNameResponse_<std::allocator<void> > GetNameResponse;

typedef boost::shared_ptr< ::qbo_face_msgs::GetNameResponse > GetNameResponsePtr;
typedef boost::shared_ptr< ::qbo_face_msgs::GetNameResponse const> GetNameResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qbo_face_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'qbo_face_msgs': ['/home/qbo/Desktop/melodia/src/qbo_face_msgs/msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc831a68fd288fbc64ac133eede0b36f";
  }

  static const char* value(const ::qbo_face_msgs::GetNameResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc831a68fd288fbcULL;
  static const uint64_t static_value2 = 0x64ac133eede0b36fULL;
};

template<class ContainerAllocator>
struct DataType< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qbo_face_msgs/GetNameResponse";
  }

  static const char* value(const ::qbo_face_msgs::GetNameResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"bool recognized\n"
"\n"
"\n"
;
  }

  static const char* value(const ::qbo_face_msgs::GetNameResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.recognized);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNameResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qbo_face_msgs::GetNameResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qbo_face_msgs::GetNameResponse_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "recognized: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.recognized);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QBO_FACE_MSGS_MESSAGE_GETNAMERESPONSE_H
