// Generated by gencpp from file qbo_face_msgs/LearnFaces.msg
// DO NOT EDIT!


#ifndef QBO_FACE_MSGS_MESSAGE_LEARNFACES_H
#define QBO_FACE_MSGS_MESSAGE_LEARNFACES_H

#include <ros/service_traits.h>


#include <qbo_face_msgs/LearnFacesRequest.h>
#include <qbo_face_msgs/LearnFacesResponse.h>


namespace qbo_face_msgs
{

struct LearnFaces
{

typedef LearnFacesRequest Request;
typedef LearnFacesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LearnFaces
} // namespace qbo_face_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qbo_face_msgs::LearnFaces > {
  static const char* value()
  {
    return "202b3c7a0bdc1cb06c9cb185e964b34a";
  }

  static const char* value(const ::qbo_face_msgs::LearnFaces&) { return value(); }
};

template<>
struct DataType< ::qbo_face_msgs::LearnFaces > {
  static const char* value()
  {
    return "qbo_face_msgs/LearnFaces";
  }

  static const char* value(const ::qbo_face_msgs::LearnFaces&) { return value(); }
};


// service_traits::MD5Sum< ::qbo_face_msgs::LearnFacesRequest> should match 
// service_traits::MD5Sum< ::qbo_face_msgs::LearnFaces > 
template<>
struct MD5Sum< ::qbo_face_msgs::LearnFacesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_face_msgs::LearnFaces >::value();
  }
  static const char* value(const ::qbo_face_msgs::LearnFacesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_face_msgs::LearnFacesRequest> should match 
// service_traits::DataType< ::qbo_face_msgs::LearnFaces > 
template<>
struct DataType< ::qbo_face_msgs::LearnFacesRequest>
{
  static const char* value()
  {
    return DataType< ::qbo_face_msgs::LearnFaces >::value();
  }
  static const char* value(const ::qbo_face_msgs::LearnFacesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qbo_face_msgs::LearnFacesResponse> should match 
// service_traits::MD5Sum< ::qbo_face_msgs::LearnFaces > 
template<>
struct MD5Sum< ::qbo_face_msgs::LearnFacesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_face_msgs::LearnFaces >::value();
  }
  static const char* value(const ::qbo_face_msgs::LearnFacesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_face_msgs::LearnFacesResponse> should match 
// service_traits::DataType< ::qbo_face_msgs::LearnFaces > 
template<>
struct DataType< ::qbo_face_msgs::LearnFacesResponse>
{
  static const char* value()
  {
    return DataType< ::qbo_face_msgs::LearnFaces >::value();
  }
  static const char* value(const ::qbo_face_msgs::LearnFacesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QBO_FACE_MSGS_MESSAGE_LEARNFACES_H
