// Generated by gencpp from file qbo_face_msgs/LearnFacesResponse.msg
// DO NOT EDIT!


#ifndef QBO_FACE_MSGS_MESSAGE_LEARNFACESRESPONSE_H
#define QBO_FACE_MSGS_MESSAGE_LEARNFACESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qbo_face_msgs
{
template <class ContainerAllocator>
struct LearnFacesResponse_
{
  typedef LearnFacesResponse_<ContainerAllocator> Type;

  LearnFacesResponse_()
    : learned(false)  {
    }
  LearnFacesResponse_(const ContainerAllocator& _alloc)
    : learned(false)  {
  (void)_alloc;
    }



   typedef uint8_t _learned_type;
  _learned_type learned;





  typedef boost::shared_ptr< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LearnFacesResponse_

typedef ::qbo_face_msgs::LearnFacesResponse_<std::allocator<void> > LearnFacesResponse;

typedef boost::shared_ptr< ::qbo_face_msgs::LearnFacesResponse > LearnFacesResponsePtr;
typedef boost::shared_ptr< ::qbo_face_msgs::LearnFacesResponse const> LearnFacesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qbo_face_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'qbo_face_msgs': ['/home/qbo/Desktop/melodia/src/qbo_face_msgs/msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9e56102f89a9558f44983cd3c0495b4";
  }

  static const char* value(const ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9e56102f89a9558ULL;
  static const uint64_t static_value2 = 0xf44983cd3c0495b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qbo_face_msgs/LearnFacesResponse";
  }

  static const char* value(const ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool learned\n"
"\n"
;
  }

  static const char* value(const ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.learned);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LearnFacesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qbo_face_msgs::LearnFacesResponse_<ContainerAllocator>& v)
  {
    s << indent << "learned: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.learned);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QBO_FACE_MSGS_MESSAGE_LEARNFACESRESPONSE_H
