// Generated by gencpp from file qbo_face_msgs/RecognizeFace.msg
// DO NOT EDIT!


#ifndef QBO_FACE_MSGS_MESSAGE_RECOGNIZEFACE_H
#define QBO_FACE_MSGS_MESSAGE_RECOGNIZEFACE_H

#include <ros/service_traits.h>


#include <qbo_face_msgs/RecognizeFaceRequest.h>
#include <qbo_face_msgs/RecognizeFaceResponse.h>


namespace qbo_face_msgs
{

struct RecognizeFace
{

typedef RecognizeFaceRequest Request;
typedef RecognizeFaceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RecognizeFace
} // namespace qbo_face_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qbo_face_msgs::RecognizeFace > {
  static const char* value()
  {
    return "133962af4d41ec98941431b15a3d4b9d";
  }

  static const char* value(const ::qbo_face_msgs::RecognizeFace&) { return value(); }
};

template<>
struct DataType< ::qbo_face_msgs::RecognizeFace > {
  static const char* value()
  {
    return "qbo_face_msgs/RecognizeFace";
  }

  static const char* value(const ::qbo_face_msgs::RecognizeFace&) { return value(); }
};


// service_traits::MD5Sum< ::qbo_face_msgs::RecognizeFaceRequest> should match 
// service_traits::MD5Sum< ::qbo_face_msgs::RecognizeFace > 
template<>
struct MD5Sum< ::qbo_face_msgs::RecognizeFaceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_face_msgs::RecognizeFace >::value();
  }
  static const char* value(const ::qbo_face_msgs::RecognizeFaceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_face_msgs::RecognizeFaceRequest> should match 
// service_traits::DataType< ::qbo_face_msgs::RecognizeFace > 
template<>
struct DataType< ::qbo_face_msgs::RecognizeFaceRequest>
{
  static const char* value()
  {
    return DataType< ::qbo_face_msgs::RecognizeFace >::value();
  }
  static const char* value(const ::qbo_face_msgs::RecognizeFaceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qbo_face_msgs::RecognizeFaceResponse> should match 
// service_traits::MD5Sum< ::qbo_face_msgs::RecognizeFace > 
template<>
struct MD5Sum< ::qbo_face_msgs::RecognizeFaceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_face_msgs::RecognizeFace >::value();
  }
  static const char* value(const ::qbo_face_msgs::RecognizeFaceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_face_msgs::RecognizeFaceResponse> should match 
// service_traits::DataType< ::qbo_face_msgs::RecognizeFace > 
template<>
struct DataType< ::qbo_face_msgs::RecognizeFaceResponse>
{
  static const char* value()
  {
    return DataType< ::qbo_face_msgs::RecognizeFace >::value();
  }
  static const char* value(const ::qbo_face_msgs::RecognizeFaceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QBO_FACE_MSGS_MESSAGE_RECOGNIZEFACE_H
