// Generated by gencpp from file qbo_face_msgs/Train.msg
// DO NOT EDIT!


#ifndef QBO_FACE_MSGS_MESSAGE_TRAIN_H
#define QBO_FACE_MSGS_MESSAGE_TRAIN_H

#include <ros/service_traits.h>


#include <qbo_face_msgs/TrainRequest.h>
#include <qbo_face_msgs/TrainResponse.h>


namespace qbo_face_msgs
{

struct Train
{

typedef TrainRequest Request;
typedef TrainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Train
} // namespace qbo_face_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qbo_face_msgs::Train > {
  static const char* value()
  {
    return "3f36036a94628f4a1bdb3c1a8d63219a";
  }

  static const char* value(const ::qbo_face_msgs::Train&) { return value(); }
};

template<>
struct DataType< ::qbo_face_msgs::Train > {
  static const char* value()
  {
    return "qbo_face_msgs/Train";
  }

  static const char* value(const ::qbo_face_msgs::Train&) { return value(); }
};


// service_traits::MD5Sum< ::qbo_face_msgs::TrainRequest> should match 
// service_traits::MD5Sum< ::qbo_face_msgs::Train > 
template<>
struct MD5Sum< ::qbo_face_msgs::TrainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_face_msgs::Train >::value();
  }
  static const char* value(const ::qbo_face_msgs::TrainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_face_msgs::TrainRequest> should match 
// service_traits::DataType< ::qbo_face_msgs::Train > 
template<>
struct DataType< ::qbo_face_msgs::TrainRequest>
{
  static const char* value()
  {
    return DataType< ::qbo_face_msgs::Train >::value();
  }
  static const char* value(const ::qbo_face_msgs::TrainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qbo_face_msgs::TrainResponse> should match 
// service_traits::MD5Sum< ::qbo_face_msgs::Train > 
template<>
struct MD5Sum< ::qbo_face_msgs::TrainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_face_msgs::Train >::value();
  }
  static const char* value(const ::qbo_face_msgs::TrainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_face_msgs::TrainResponse> should match 
// service_traits::DataType< ::qbo_face_msgs::Train > 
template<>
struct DataType< ::qbo_face_msgs::TrainResponse>
{
  static const char* value()
  {
    return DataType< ::qbo_face_msgs::Train >::value();
  }
  static const char* value(const ::qbo_face_msgs::TrainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QBO_FACE_MSGS_MESSAGE_TRAIN_H
