(cl:defpackage qbo_listen-srv
  (:use )
  (:export
   "FREE_TRAIN"
   "<FREE_TRAIN-REQUEST>"
   "FREE_TRAIN-REQUEST"
   "<FREE_TRAIN-RESPONSE>"
   "FREE_TRAIN-RESPONSE"
   "NEW_WORD"
   "<NEW_WORD-REQUEST>"
   "NEW_WORD-REQUEST"
   "<NEW_WORD-RESPONSE>"
   "NEW_WORD-RESPONSE"
   "SPELL_WORD"
   "<SPELL_WORD-REQUEST>"
   "SPELL_WORD-REQUEST"
   "<SPELL_WORD-RESPONSE>"
   "SPELL_WORD-RESPONSE"
   "TRAIN_WORD"
   "<TRAIN_WORD-REQUEST>"
   "TRAIN_WORD-REQUEST"
   "<TRAIN_WORD-RESPONSE>"
   "TRAIN_WORD-RESPONSE"
  ))

