// Generated by gencpp from file qbo_talk/Text2Speach.msg
// DO NOT EDIT!


#ifndef QBO_TALK_MESSAGE_TEXT2SPEACH_H
#define QBO_TALK_MESSAGE_TEXT2SPEACH_H

#include <ros/service_traits.h>


#include <qbo_talk/Text2SpeachRequest.h>
#include <qbo_talk/Text2SpeachResponse.h>


namespace qbo_talk
{

struct Text2Speach
{

typedef Text2SpeachRequest Request;
typedef Text2SpeachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Text2Speach
} // namespace qbo_talk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qbo_talk::Text2Speach > {
  static const char* value()
  {
    return "2fb3aa2736d70ecbfc297d3d9b879661";
  }

  static const char* value(const ::qbo_talk::Text2Speach&) { return value(); }
};

template<>
struct DataType< ::qbo_talk::Text2Speach > {
  static const char* value()
  {
    return "qbo_talk/Text2Speach";
  }

  static const char* value(const ::qbo_talk::Text2Speach&) { return value(); }
};


// service_traits::MD5Sum< ::qbo_talk::Text2SpeachRequest> should match 
// service_traits::MD5Sum< ::qbo_talk::Text2Speach > 
template<>
struct MD5Sum< ::qbo_talk::Text2SpeachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_talk::Text2Speach >::value();
  }
  static const char* value(const ::qbo_talk::Text2SpeachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_talk::Text2SpeachRequest> should match 
// service_traits::DataType< ::qbo_talk::Text2Speach > 
template<>
struct DataType< ::qbo_talk::Text2SpeachRequest>
{
  static const char* value()
  {
    return DataType< ::qbo_talk::Text2Speach >::value();
  }
  static const char* value(const ::qbo_talk::Text2SpeachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qbo_talk::Text2SpeachResponse> should match 
// service_traits::MD5Sum< ::qbo_talk::Text2Speach > 
template<>
struct MD5Sum< ::qbo_talk::Text2SpeachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_talk::Text2Speach >::value();
  }
  static const char* value(const ::qbo_talk::Text2SpeachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_talk::Text2SpeachResponse> should match 
// service_traits::DataType< ::qbo_talk::Text2Speach > 
template<>
struct DataType< ::qbo_talk::Text2SpeachResponse>
{
  static const char* value()
  {
    return DataType< ::qbo_talk::Text2Speach >::value();
  }
  static const char* value(const ::qbo_talk::Text2SpeachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QBO_TALK_MESSAGE_TEXT2SPEACH_H
