// Generated by gencpp from file qbo_talk/Text2SpeachRequest.msg
// DO NOT EDIT!


#ifndef QBO_TALK_MESSAGE_TEXT2SPEACHREQUEST_H
#define QBO_TALK_MESSAGE_TEXT2SPEACHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qbo_talk
{
template <class ContainerAllocator>
struct Text2SpeachRequest_
{
  typedef Text2SpeachRequest_<ContainerAllocator> Type;

  Text2SpeachRequest_()
    : command()  {
    }
  Text2SpeachRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Text2SpeachRequest_

typedef ::qbo_talk::Text2SpeachRequest_<std::allocator<void> > Text2SpeachRequest;

typedef boost::shared_ptr< ::qbo_talk::Text2SpeachRequest > Text2SpeachRequestPtr;
typedef boost::shared_ptr< ::qbo_talk::Text2SpeachRequest const> Text2SpeachRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qbo_talk

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::qbo_talk::Text2SpeachRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qbo_talk/Text2SpeachRequest";
  }

  static const char* value(const ::qbo_talk::Text2SpeachRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"string command\n"
;
  }

  static const char* value(const ::qbo_talk::Text2SpeachRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Text2SpeachRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qbo_talk::Text2SpeachRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qbo_talk::Text2SpeachRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QBO_TALK_MESSAGE_TEXT2SPEACHREQUEST_H
