// Generated by gencpp from file qbo_system_info/AskInfo.msg
// DO NOT EDIT!


#ifndef QBO_SYSTEM_INFO_MESSAGE_ASKINFO_H
#define QBO_SYSTEM_INFO_MESSAGE_ASKINFO_H

#include <ros/service_traits.h>


#include <qbo_system_info/AskInfoRequest.h>
#include <qbo_system_info/AskInfoResponse.h>


namespace qbo_system_info
{

struct AskInfo
{

typedef AskInfoRequest Request;
typedef AskInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AskInfo
} // namespace qbo_system_info


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qbo_system_info::AskInfo > {
  static const char* value()
  {
    return "2114094fd794b6de43079d7511fd7383";
  }

  static const char* value(const ::qbo_system_info::AskInfo&) { return value(); }
};

template<>
struct DataType< ::qbo_system_info::AskInfo > {
  static const char* value()
  {
    return "qbo_system_info/AskInfo";
  }

  static const char* value(const ::qbo_system_info::AskInfo&) { return value(); }
};


// service_traits::MD5Sum< ::qbo_system_info::AskInfoRequest> should match 
// service_traits::MD5Sum< ::qbo_system_info::AskInfo > 
template<>
struct MD5Sum< ::qbo_system_info::AskInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_system_info::AskInfo >::value();
  }
  static const char* value(const ::qbo_system_info::AskInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_system_info::AskInfoRequest> should match 
// service_traits::DataType< ::qbo_system_info::AskInfo > 
template<>
struct DataType< ::qbo_system_info::AskInfoRequest>
{
  static const char* value()
  {
    return DataType< ::qbo_system_info::AskInfo >::value();
  }
  static const char* value(const ::qbo_system_info::AskInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qbo_system_info::AskInfoResponse> should match 
// service_traits::MD5Sum< ::qbo_system_info::AskInfo > 
template<>
struct MD5Sum< ::qbo_system_info::AskInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_system_info::AskInfo >::value();
  }
  static const char* value(const ::qbo_system_info::AskInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_system_info::AskInfoResponse> should match 
// service_traits::DataType< ::qbo_system_info::AskInfo > 
template<>
struct DataType< ::qbo_system_info::AskInfoResponse>
{
  static const char* value()
  {
    return DataType< ::qbo_system_info::AskInfo >::value();
  }
  static const char* value(const ::qbo_system_info::AskInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QBO_SYSTEM_INFO_MESSAGE_ASKINFO_H
