// Generated by gencpp from file qbo_listen/free_train.msg
// DO NOT EDIT!


#ifndef QBO_LISTEN_MESSAGE_FREE_TRAIN_H
#define QBO_LISTEN_MESSAGE_FREE_TRAIN_H

#include <ros/service_traits.h>


#include <qbo_listen/free_trainRequest.h>
#include <qbo_listen/free_trainResponse.h>


namespace qbo_listen
{

struct free_train
{

typedef free_trainRequest Request;
typedef free_trainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct free_train
} // namespace qbo_listen


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qbo_listen::free_train > {
  static const char* value()
  {
    return "719c501bbbeb289704ee5d42501844db";
  }

  static const char* value(const ::qbo_listen::free_train&) { return value(); }
};

template<>
struct DataType< ::qbo_listen::free_train > {
  static const char* value()
  {
    return "qbo_listen/free_train";
  }

  static const char* value(const ::qbo_listen::free_train&) { return value(); }
};


// service_traits::MD5Sum< ::qbo_listen::free_trainRequest> should match 
// service_traits::MD5Sum< ::qbo_listen::free_train > 
template<>
struct MD5Sum< ::qbo_listen::free_trainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_listen::free_train >::value();
  }
  static const char* value(const ::qbo_listen::free_trainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_listen::free_trainRequest> should match 
// service_traits::DataType< ::qbo_listen::free_train > 
template<>
struct DataType< ::qbo_listen::free_trainRequest>
{
  static const char* value()
  {
    return DataType< ::qbo_listen::free_train >::value();
  }
  static const char* value(const ::qbo_listen::free_trainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qbo_listen::free_trainResponse> should match 
// service_traits::MD5Sum< ::qbo_listen::free_train > 
template<>
struct MD5Sum< ::qbo_listen::free_trainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_listen::free_train >::value();
  }
  static const char* value(const ::qbo_listen::free_trainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_listen::free_trainResponse> should match 
// service_traits::DataType< ::qbo_listen::free_train > 
template<>
struct DataType< ::qbo_listen::free_trainResponse>
{
  static const char* value()
  {
    return DataType< ::qbo_listen::free_train >::value();
  }
  static const char* value(const ::qbo_listen::free_trainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QBO_LISTEN_MESSAGE_FREE_TRAIN_H
