// Generated by gencpp from file qbo_listen/new_word.msg
// DO NOT EDIT!


#ifndef QBO_LISTEN_MESSAGE_NEW_WORD_H
#define QBO_LISTEN_MESSAGE_NEW_WORD_H

#include <ros/service_traits.h>


#include <qbo_listen/new_wordRequest.h>
#include <qbo_listen/new_wordResponse.h>


namespace qbo_listen
{

struct new_word
{

typedef new_wordRequest Request;
typedef new_wordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct new_word
} // namespace qbo_listen


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qbo_listen::new_word > {
  static const char* value()
  {
    return "5c002061418e8070e6be74c25693fdf1";
  }

  static const char* value(const ::qbo_listen::new_word&) { return value(); }
};

template<>
struct DataType< ::qbo_listen::new_word > {
  static const char* value()
  {
    return "qbo_listen/new_word";
  }

  static const char* value(const ::qbo_listen::new_word&) { return value(); }
};


// service_traits::MD5Sum< ::qbo_listen::new_wordRequest> should match 
// service_traits::MD5Sum< ::qbo_listen::new_word > 
template<>
struct MD5Sum< ::qbo_listen::new_wordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_listen::new_word >::value();
  }
  static const char* value(const ::qbo_listen::new_wordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_listen::new_wordRequest> should match 
// service_traits::DataType< ::qbo_listen::new_word > 
template<>
struct DataType< ::qbo_listen::new_wordRequest>
{
  static const char* value()
  {
    return DataType< ::qbo_listen::new_word >::value();
  }
  static const char* value(const ::qbo_listen::new_wordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qbo_listen::new_wordResponse> should match 
// service_traits::MD5Sum< ::qbo_listen::new_word > 
template<>
struct MD5Sum< ::qbo_listen::new_wordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_listen::new_word >::value();
  }
  static const char* value(const ::qbo_listen::new_wordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_listen::new_wordResponse> should match 
// service_traits::DataType< ::qbo_listen::new_word > 
template<>
struct DataType< ::qbo_listen::new_wordResponse>
{
  static const char* value()
  {
    return DataType< ::qbo_listen::new_word >::value();
  }
  static const char* value(const ::qbo_listen::new_wordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QBO_LISTEN_MESSAGE_NEW_WORD_H
