// Generated by gencpp from file qbo_listen/train_word.msg
// DO NOT EDIT!


#ifndef QBO_LISTEN_MESSAGE_TRAIN_WORD_H
#define QBO_LISTEN_MESSAGE_TRAIN_WORD_H

#include <ros/service_traits.h>


#include <qbo_listen/train_wordRequest.h>
#include <qbo_listen/train_wordResponse.h>


namespace qbo_listen
{

struct train_word
{

typedef train_wordRequest Request;
typedef train_wordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct train_word
} // namespace qbo_listen


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qbo_listen::train_word > {
  static const char* value()
  {
    return "67eda7b60c88a74182afde47ca6a3f77";
  }

  static const char* value(const ::qbo_listen::train_word&) { return value(); }
};

template<>
struct DataType< ::qbo_listen::train_word > {
  static const char* value()
  {
    return "qbo_listen/train_word";
  }

  static const char* value(const ::qbo_listen::train_word&) { return value(); }
};


// service_traits::MD5Sum< ::qbo_listen::train_wordRequest> should match 
// service_traits::MD5Sum< ::qbo_listen::train_word > 
template<>
struct MD5Sum< ::qbo_listen::train_wordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_listen::train_word >::value();
  }
  static const char* value(const ::qbo_listen::train_wordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_listen::train_wordRequest> should match 
// service_traits::DataType< ::qbo_listen::train_word > 
template<>
struct DataType< ::qbo_listen::train_wordRequest>
{
  static const char* value()
  {
    return DataType< ::qbo_listen::train_word >::value();
  }
  static const char* value(const ::qbo_listen::train_wordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qbo_listen::train_wordResponse> should match 
// service_traits::MD5Sum< ::qbo_listen::train_word > 
template<>
struct MD5Sum< ::qbo_listen::train_wordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qbo_listen::train_word >::value();
  }
  static const char* value(const ::qbo_listen::train_wordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qbo_listen::train_wordResponse> should match 
// service_traits::DataType< ::qbo_listen::train_word > 
template<>
struct DataType< ::qbo_listen::train_wordResponse>
{
  static const char* value()
  {
    return DataType< ::qbo_listen::train_word >::value();
  }
  static const char* value(const ::qbo_listen::train_wordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QBO_LISTEN_MESSAGE_TRAIN_WORD_H
